---
- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
    daemon_reload: true
- name: Restart kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted
    daemon_reload: true
